# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# This is a good reference:
# https://github.com/Bioconductor/BiocManager/blob/master/appveyor.yml

cache:
  - C:\RLibrary

environment:
  global:
    _R_CHECK_FORCE_SUGGESTS_: false
    R_ARCH: x64
    USE_RTOOLS: true
    R_CHECK_ARGS: "--no-manual --timings"
    R_LIBCURL_SSL_REVOKE_BEST_EFFORT: "TRUE"
    CURL_SSL_BACKEND: "openssl"

  matrix:
  - R_VERSION: release
    BIOC_USE_DEVEL: FALSE

build_script:
  - echo Current directory=%CD%
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_r Seurat

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
