# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kmeans_centers <- function(X, K, verbose) {
    .Call('_harmony_kmeans_centers', PACKAGE = 'harmony', X, K, verbose)
}

scaleRows_dgc <- function(x, p, i, ncol, nrow, thresh) {
    .Call('_harmony_scaleRows_dgc', PACKAGE = 'harmony', x, p, i, ncol, nrow, thresh)
}

find_lambda_cpp <- function(alpha, cluster_E) {
    .Call('_harmony_find_lambda_cpp', PACKAGE = 'harmony', alpha, cluster_E)
}

